name: flutter_playground
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-239.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true