name: flutter_playground
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-239.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  http: ^1.2.1
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true